-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2026-06-20 18:47:46 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE AERONAVE 
    ( 
     Inscricao  VARCHAR (6)  NOT NULL , 
     Modelo     VARCHAR (10)  NOT NULL , 
     N_Assentos INT  NOT NULL 
    ) 
;

ALTER TABLE AERONAVE 
    ADD CONSTRAINT AERONAVE_PK PRIMARY KEY ( Inscricao ) ;

CREATE TABLE AEROPORTO 
    ( 
     Identificador VARCHAR (3)  NOT NULL , 
     Cidade        VARCHAR (30)  NOT NULL , 
     Estado        VARCHAR (2)  NOT NULL 
    ) 
;

ALTER TABLE AEROPORTO 
    ADD CONSTRAINT AEROPORTO_PK PRIMARY KEY ( Identificador ) ;

CREATE TABLE PASSAGEM 
    ( 
     Data                    DATE  NOT NULL , 
     Hora                    TIME  NOT NULL , 
     VOO_ID                  INT   NOT NULL , 
     PESSOA_CPF_COMPRA       VARCHAR (11)  NOT NULL , 
     AEROPORTO_Identificador VARCHAR (3)  NOT NULL , 
     PASSAGEIRO_CPF          VARCHAR (11) , 
     Valor                   INT  NOT NULL , 
     Assento                 VARCHAR (4)  NOT NULL,
	 PNome_Passageiro		 VARCHAR (15) NULL,
	 UNome_Passageiro		 VARCHAR (15) NULL
    ) 
;

ALTER TABLE PASSAGEM 
    ADD CONSTRAINT PASSAGEM_PK PRIMARY KEY ( Data, Hora, VOO_ID, PESSOA_CPF_COMPRA, AEROPORTO_Identificador, Assento ) ;

CREATE TABLE PESSOA 
    ( 
     CPF             VARCHAR (11)  NOT NULL , 
     P_Nome          VARCHAR (15)  NOT NULL , 
     U_Nome          VARCHAR (15)  NOT NULL , 
     Email           VARCHAR (30) , 
     Data_Nascimento DATE , 
     Senha           VARCHAR (15) , 
     Telefone        VARCHAR (14) , 
     Endereco        VARCHAR (50) 
    ) 
;

ALTER TABLE PESSOA 
    ADD CONSTRAINT PESSOA_PK PRIMARY KEY ( CPF ) ;

CREATE TABLE VOO 
    ( 
     ID                   INT NOT NULL , 
     AERONAVE_Inscricao   VARCHAR (6)  NOT NULL , 
     AEROPORTO_ID_CHEGADA VARCHAR (3)  NOT NULL , 
     AEROPORTO_ID_PARTIDA VARCHAR (3)  NOT NULL 
    ) 
;

ALTER TABLE VOO 
    ADD CONSTRAINT VOO_PK PRIMARY KEY ( ID ) ;

ALTER TABLE PASSAGEM 
    ADD CONSTRAINT PASSAGEM_AEROPORTO_FK FOREIGN KEY 
    ( 
     AEROPORTO_Identificador
    ) 
    REFERENCES AEROPORTO 
    ( 
     Identificador
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE PASSAGEM 
    ADD CONSTRAINT PASSAGEM_PESSOA_FK FOREIGN KEY 
    ( 
     PESSOA_CPF_COMPRA
    ) 
    REFERENCES PESSOA 
    ( 
     CPF
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE PASSAGEM 
    ADD CONSTRAINT PASSAGEM_PESSOA_FKv2 FOREIGN KEY 
    ( 
     PASSAGEIRO_CPF
    ) 
    REFERENCES PESSOA 
    ( 
     CPF
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE PASSAGEM 
    ADD CONSTRAINT PASSAGEM_VOO_FK FOREIGN KEY 
    ( 
     VOO_ID
    ) 
    REFERENCES VOO 
    ( 
     ID
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE VOO 
    ADD CONSTRAINT VOO_AERONAVE_FK FOREIGN KEY 
    ( 
     AERONAVE_Inscricao
    ) 
    REFERENCES AERONAVE 
    ( 
     Inscricao
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE VOO 
    ADD CONSTRAINT VOO_AEROPORTO_FK FOREIGN KEY 
    ( 
     AEROPORTO_ID_CHEGADA
    ) 
    REFERENCES AEROPORTO 
    ( 
     Identificador
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE VOO 
    ADD CONSTRAINT VOO_AEROPORTO_FKv2 FOREIGN KEY 
    ( 
     AEROPORTO_ID_PARTIDA
    ) 
    REFERENCES AEROPORTO 
    ( 
     Identificador
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE PASSAGEM
    ADD COLUMN id SERIAL;

-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0



-- INSERTS
INSERT INTO AERONAVE VALUES('PP-WCD', 'A320', '10');
INSERT INTO AERONAVE VALUES('PP-DCW', 'A330', '30');
INSERT INTO AERONAVE VALUES('PP-AAA', 'B787', '50');
INSERT INTO AERONAVE VALUES('PP-BBB', 'B707', '10');
INSERT INTO AERONAVE VALUES('PP-CCC', 'A380', '50');
SELECT * FROM AERONAVE;

INSERT INTO AEROPORTO VALUES('CNF', 'Belo Horizonte', 'MG');
INSERT INTO AEROPORTO VALUES('GRU', 'Guarulhos', 'SP');
INSERT INTO AEROPORTO VALUES('GIG', 'Rio de Janeiro', 'RJ');
INSERT INTO AEROPORTO VALUES('FLO', 'Florianopolis', 'SC');
SELECT * FROM AEROPORTO;

INSERT INTO VOO VALUES(1, 'PP-WCD', 'GRU', 'CNF');
INSERT INTO VOO VALUES(2, 'PP-DCW', 'GIG', 'FLO');
INSERT INTO VOO VALUES(3, 'PP-AAA', 'FLO', 'CNF');
INSERT INTO VOO VALUES(4, 'PP-BBB', 'GRU', 'GIG');
SELECT * FROM VOO;

INSERT INTO PESSOA VALUES('16114405641', 'Arthur', 'Oliveira', 'email.teste@email.com', '13/05/2003', '1234', '31993184163', 'Rua A');
INSERT INTO PESSOA VALUES('00000000000', 'ADMIN', 'ADMIN', NULL, NULL, '1234', NULL, NULL);

INSERT INTO PASSAGEM VALUES('05/07/2026','08:00:00',1,'00000000000','GRU',NULL,350,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('07/07/2026','09:20:00',1,'00000000000','GRU',NULL,350,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('10/07/2026','14:45:00',1,'00000000000','GRU',NULL,350,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('15/07/2026','18:30:00',1,'00000000000','GRU',NULL,350,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('20/07/2026','07:10:00',1,'00000000000','GRU',NULL,350,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('06/07/2026','10:30:00',2,'00000000000','GIG',NULL,480,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('09/07/2026','13:15:00',2,'00000000000','GIG',NULL,480,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('14/07/2026','16:50:00',2,'00000000000','GIG',NULL,480,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('21/07/2026','11:40:00',2,'00000000000','GIG',NULL,480,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('28/07/2026','19:25:00',2,'00000000000','GIG',NULL,480,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('08/07/2026','06:50:00',3,'00000000000','FLO',NULL,420,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('13/07/2026','08:35:00',3,'00000000000','FLO',NULL,420,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('18/07/2026','15:10:00',3,'00000000000','FLO',NULL,420,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('25/07/2026','20:00:00',3,'00000000000','FLO',NULL,420,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('30/07/2026','09:55:00',3,'00000000000','FLO',NULL,420,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('11/07/2026','07:40:00',4,'00000000000','GRU',NULL,300,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('16/07/2026','12:00:00',4,'00000000000','GRU',NULL,300,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('22/07/2026','17:15:00',4,'00000000000','GRU',NULL,300,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('29/07/2026','21:30:00',4,'00000000000','GRU',NULL,300,'1A',NULL,NULL);
INSERT INTO PASSAGEM VALUES('03/08/2026','10:20:00',4,'00000000000','GRU',NULL,300,'1A',NULL,NULL);

-- TESTE PASSAGEM POS DATA E HORA
INSERT INTO PASSAGEM VALUES('25/06/2026', '20:58:40',4,'00000000000','GRU',NULL,300,'1A',NULL,NULL);
